## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix stores a matrix and its inverse in another environment
## It returns a list of 4 functions that gives access to setting the matrix, caching the inverse and retrieving them

makeCacheMatrix <- function(x = matrix()) {
     invmat <- NULL
     set <- function(y) {
          x <<- y
          invmat <<- NULL
     }
     get <- function() x
     setinv <- function(z) {invmat <<- z}
     getinv <- function() {invmat}
     list(set = set, get = get,
          setinv = setinv,
          getinv = getinv)
}


## Using one of the Matrices generated by makeCacheMatrix, cacheSolve retunns its inverse matrix.
## If it has been calculated once, the inverse is cached and the function recovers it from the cache.
## If not, the inverse is calculated and cached

cacheSolve <- function(x) {
     invmat <- x$getinv()
     if(!is.null(invmat)) {
          message("getting cached data")
          return(invmat)
     }
     data <- x$get()
     invmat <- solve(data)
     x$setinv(invmat)
     invmat
}
